# Esercizio Reshaping, Istruzioni

Popolazione (in migliaia) nelle regioni d'Italia per titolo di studio: http://dati.istat.it/Index.aspx?QueryId=26176

In [1]:
import pandas as pd

df = pd.read_csv("studio.csv", encoding='latin1')

df

,Territorio,Sesso,Classe di età,Titolo di studio,TIME,Value
0,Piemonte,maschi,15 anni e più,"licenza di scuola elementare, nessun titolo di...",2018,226.200
1,Piemonte,maschi,15 anni e più,"licenza di scuola elementare, nessun titolo di...",2019,211.578
2,Piemonte,maschi,15 anni e più,licenza di scuola media,2018,656.363
3,Piemonte,maschi,15 anni e più,licenza di scuola media,2019,651.879
4,Piemonte,maschi,15 anni e più,diploma 2-3 anni (qualifica professionale),2018,147.788
...,...,...,...,...,...,...
787,Sardegna,totale,15 anni e più,diploma 4-5 anni (maturità),2019,419.629
788,Sardegna,totale,15 anni e più,laurea e post-laurea,2018,176.258
789,Sardegna,totale,15 anni e più,laurea e post-laurea,2019,188.533
790,Sardegna,totale,15 anni e più,totale,2018,1450.465
791,Sardegna,totale,15 anni e più,totale,2019,1445.869

In [69]:
df.Territorio.value_counts() # 20 regioni piu' provincia autonoma di Bolzano e Trento

Provincia Autonoma Trento             36
Piemonte                              36
Provincia Autonoma Bolzano / Bozen    36
Friuli-Venezia Giulia                 36
Liguria                               36
Basilicata                            36
Umbria                                36
Veneto                                36
Marche                                36
Lazio                                 36
Puglia                                36
Lombardia                             36
Toscana                               36
Molise                                36
Trentino Alto Adige / Südtirol        36
Calabria                              36
Emilia-Romagna                        36
Sicilia                               36
Campania                              36
Sardegna                              36
Valle d'Aosta / Vallée d'Aoste        36
Abruzzo                               36
Name: Territorio, dtype: int64

In [75]:
df.Sesso.value_counts()

totale     264
femmine    264
maschi     264
Name: Sesso, dtype: int64

In [77]:
df["Classe di età"].value_counts()

15 anni e più    792
Name: Classe di età, dtype: int64

In [72]:
df.TIME.value_counts() # tipo int

2019    396
2018    396
Name: TIME, dtype: int64

In [73]:
df["Titolo di studio"].value_counts()

totale                                                   132
diploma 4-5 anni (maturità)                              132
licenza di scuola media                                  132
diploma 2-3 anni (qualifica professionale)               132
laurea e post-laurea                                     132
licenza di scuola elementare, nessun titolo di studio    132
Name: Titolo di studio, dtype: int64

#####  Elimina (in maniera permanente) dal dataframe tutte le righe che contengono sotto la colonna "Sesso" la stringa "totale"

#####  Elimina (in maniera permanente) dal dataframe tutte le righe che contengono sotto la colonna "Titolo di Studio" la stringa "totale"

##### 2 - Visualizza il seguente output

- devi ottenere il numero totale di persone per ogni regione per anno

                                            Value
Territorio                         TIME
Abruzzo                            2018  1144.803
                                   2019  1141.831
Basilicata                         2018   495.227
                                   2019   492.004
Calabria                           2018  1685.481
                                   2019  1678.471
Campania                           2018  4948.019
                                   2019  4936.763
Emilia-Romagna                     2018  3832.478
                                   2019  3841.515
Friuli-Venezia Giulia              2018  1058.068
                                   2019  1057.567
Lazio                              2018  5059.488
                                   2019  5052.360
Liguria                            2018  1367.161
                                   2019  1361.733
Lombardia                          2018  8591.619
                                   2019  8623.644
Marche                             2018  1326.417
                                   2019  1323.177
Molise                             2018   269.960
                                   2019   267.517
Piemonte                           2018  3782.210
                                   2019  3772.302
Provincia Autonoma Bolzano / Bozen 2018   438.282
                                   2019   440.830
Provincia Autonoma Trento          2018   455.859
                                   2019   457.420
Puglia                             2018  3494.706
                                   2019  3485.824
Sardegna                           2018  1450.466
                                   2019  1445.868
Sicilia                            2018  4299.334
                                   2019  4281.707
Toscana                            2018  3246.426
                                   2019  3243.729
Trentino Alto Adige / Südtirol     2018   894.145
                                   2019   898.248
Umbria                             2018   767.236
                                   2019   765.844
Valle d'Aosta / Vallée d'Aoste     2018   108.168
                                   2019   108.003
Veneto                             2018  4205.818
                                   2019  4215.315

##### Visualizza il seguente output
- simile a prima ma devi distinguere la somma totale di persone tra maschi e femmine

Sesso                                     femmine    maschi
Territorio                         TIME
Abruzzo                            2018   591.799   553.004
                                   2019   589.937   551.894
Basilicata                         2018   254.096   241.131
                                   2019   252.515   239.489
Calabria                           2018   867.238   818.243
                                   2019   863.039   815.432
Campania                           2018  2559.907  2388.112
                                   2019  2555.248  2381.515
Emilia-Romagna                     2018  1988.410  1844.068
                                   2019  1991.602  1849.913
Friuli-Venezia Giulia              2018   548.003   510.065
                                   2019   547.274   510.293
Lazio                              2018  2639.612  2419.876
                                   2019  2637.677  2414.683
Liguria                            2018   720.045   647.116
                                   2019   716.837   644.896
Lombardia                          2018  4420.595  4171.024
                                   2019  4434.175  4189.469
Marche                             2018   688.239   638.178
                                   2019   686.183   636.994
Molise                             2018   138.527   131.433
                                   2019   137.472   130.045
Piemonte                           2018  1962.621  1819.589
                                   2019  1956.467  1815.835
Provincia Autonoma Bolzano / Bozen 2018   224.232   214.050
                                   2019   225.400   215.430
Provincia Autonoma Trento          2018   233.872   221.987
                                   2019   234.595   222.825
Puglia                             2018  1811.535  1683.171
                                   2019  1806.127  1679.697
Sardegna                           2018   743.332   707.134
                                   2019   741.220   704.648
Sicilia                            2018  2230.808  2068.526
                                   2019  2221.371  2060.336
Toscana                            2018  1696.978  1549.448
                                   2019  1694.858  1548.871
Trentino Alto Adige / Südtirol     2018   458.107   436.038
                                   2019   459.994   438.254
Umbria                             2018   401.852   365.384
                                   2019   400.724   365.120
Valle d'Aosta / Vallée d'Aoste     2018    55.820    52.348
                                   2019    55.778    52.225
Veneto                             2018  2163.541  2042.277
                                   2019  2166.444  2048.871

##### ottieni il seguente output
- il numero totale di persone nel 2018 e 2019, per ogni regione distinguendo tra maschi e femmine

Sesso                                femmine              maschi
TIME                                    2018      2019      2018      2019
Territorio
Abruzzo                             1183.597  1179.873  1106.008  1103.788
Basilicata                           508.192   505.031   482.263   478.978
Calabria                            1734.477  1726.077  1636.486  1630.864
Campania                            5119.814  5110.496  4776.224  4763.031
Emilia-Romagna                      3976.820  3983.203  3688.134  3699.826
Friuli-Venezia Giulia               1096.007  1094.548  1020.129  1020.586
Lazio                               5279.225  5275.354  4839.751  4829.367
Liguria                             1440.090  1433.674  1294.232  1289.793
Lombardia                           8841.189  8868.350  8342.048  8378.938
Marche                              1376.477  1372.365  1276.356  1273.988
Molise                               277.055   274.944   262.865   260.090
Piemonte                            3925.243  3912.933  3639.178  3631.670
Provincia Autonoma Bolzano / Bozen   448.465   450.800   428.101   430.860
Provincia Autonoma Trento            467.744   469.190   443.975   445.650
Puglia                              3623.069  3612.254  3366.342  3359.393
Sardegna                            1486.664  1482.440  1414.267  1409.297
Sicilia                             4461.616  4442.742  4137.052  4120.673
Toscana                             3393.955  3389.715  3098.896  3097.743
Trentino Alto Adige / Südtirol       916.212   919.989   872.076   876.509
Umbria                               803.703   801.448   730.768   730.241
Valle d'Aosta / Vallée d'Aoste       111.640   111.555   104.696   104.450
Veneto                              4327.082  4332.890  4084.555  4097.741

#### ottieni il seguente output
- Numero totale di persone per titolo di studio per regione negli anni 2018 e 2019

TIME                                                                     2018  \
Titolo di studio                   diploma 2-3 anni (qualifica professionale)
Territorio
Abruzzo                                                                40.687
Basilicata                                                             17.559
Calabria                                                               33.025
Campania                                                              128.247
Emilia-Romagna                                                        285.886
Friuli-Venezia Giulia                                                  95.105
Lazio                                                                 144.283
Liguria                                                                85.083
Lombardia                                                             721.819
Marche                                                                 62.275
Molise                                                                  5.331
Piemonte                                                              293.027
Provincia Autonoma Bolzano / Bozen                                     75.065
Provincia Autonoma Trento                                              64.426
Puglia                                                                 70.932
Sardegna                                                               27.779
Sicilia                                                                75.957
Toscana                                                               149.191
Trentino Alto Adige / Südtirol                                        139.492
Umbria                                                                 40.224
Valle d'Aosta / Vallée d'Aoste                                          6.808
Veneto                                                                412.675

TIME                                                            \
Titolo di studio                   diploma 4-5 anni (maturità)
Territorio
Abruzzo                                                406.532
Basilicata                                             170.799
Calabria                                               532.515
Campania                                              1536.610
Emilia-Romagna                                        1183.072
Friuli-Venezia Giulia                                  322.117
Lazio                                                 1845.547
Liguria                                                435.309
Lombardia                                             2450.034
Marche                                                 426.526
Molise                                                  89.573
Piemonte                                              1081.120
Provincia Autonoma Bolzano / Bozen                     105.297
Provincia Autonoma Trento                              122.281
Puglia                                                 993.650
Sardegna                                               404.285
Sicilia                                               1303.422
Toscana                                               1030.709
Trentino Alto Adige / Südtirol                         227.578
Umbria                                                 263.259
Valle d'Aosta / Vallée d'Aoste                          31.776
Veneto                                                1192.027

TIME                                                     \
Titolo di studio                   laurea e post-laurea
Territorio
Abruzzo                                         170.529
Basilicata                                       59.507
Calabria                                        194.005
Campania                                        606.136
Emilia-Romagna                                  640.581
Friuli-Venezia Giulia                           162.434
Lazio                                          1025.094
Liguria                                         222.944
Lombardia                                      1375.476
Marche                                          198.592
Molise                                           39.652
Piemonte                                        539.200
Provincia Autonoma Bolzano / Bozen               56.024
Provincia Autonoma Trento                        71.440
Puglia                                          391.813
Sardegna                                        176.258
Sicilia                                         474.962
Toscana                                         518.930
Trentino Alto Adige / Südtirol                  127.465
Umbria                                          118.574
Valle d'Aosta / Vallée d'Aoste                   14.958
Veneto                                          587.174

TIME                                                                                      \
Titolo di studio                   licenza di scuola elementare, nessun titolo di studio
Territorio
Abruzzo                                                                       194.931
Basilicata                                                                    100.973
Calabria                                                                      374.276
Campania                                                                      944.048
Emilia-Romagna                                                                604.459
Friuli-Venezia Giulia                                                         151.604
Lazio                                                                         593.767
Liguria                                                                       195.873
Lombardia                                                                    1274.325
Marche                                                                        237.288
Molise                                                                         53.504
Piemonte                                                                      605.004
Provincia Autonoma Bolzano / Bozen                                             60.436
Provincia Autonoma Trento                                                      57.201
Puglia                                                                        800.542
Sardegna                                                                      260.614
Sicilia                                                                       882.953
Toscana                                                                       582.542
Trentino Alto Adige / Südtirol                                                117.637
Umbria                                                                        133.390
Valle d'Aosta / Vallée d'Aoste                                                 16.088
Veneto                                                                        697.759

TIME                                                        \
Titolo di studio                   licenza di scuola media
Territorio
Abruzzo                                            332.124
Basilicata                                         146.389
Calabria                                           551.660
Campania                                          1732.978
Emilia-Romagna                                    1118.480
Friuli-Venezia Giulia                              326.808
Lazio                                             1450.797
Liguria                                            427.952
Lombardia                                         2769.965
Marche                                             401.736
Molise                                              81.900
Piemonte                                          1263.859
Provincia Autonoma Bolzano / Bozen                 141.460
Provincia Autonoma Trento                          140.511
Puglia                                            1237.769
Sardegna                                           581.530
Sicilia                                           1562.040
Toscana                                            965.054
Trentino Alto Adige / Südtirol                     281.973
Umbria                                             211.789
Valle d'Aosta / Vallée d'Aoste                      38.538
Veneto                                            1316.183

TIME                                                                     2019  \
Titolo di studio                   diploma 2-3 anni (qualifica professionale)
Territorio
Abruzzo                                                                42.116
Basilicata                                                             16.718
Calabria                                                               30.568
Campania                                                              122.410
Emilia-Romagna                                                        284.390
Friuli-Venezia Giulia                                                  99.229
Lazio                                                                 131.994
Liguria                                                                91.380
Lombardia                                                             719.691
Marche                                                                 69.176
Molise                                                                  5.365
Piemonte                                                              310.186
Provincia Autonoma Bolzano / Bozen                                     73.612
Provincia Autonoma Trento                                              65.997
Puglia                                                                 69.666
Sardegna                                                               28.101
Sicilia                                                                73.720
Toscana                                                               163.795
Trentino Alto Adige / Südtirol                                        139.609
Umbria                                                                 40.149
Valle d'Aosta / Vallée d'Aoste                                          6.685
Veneto                                                                416.690

TIME                                                            \
Titolo di studio                   diploma 4-5 anni (maturità)
Territorio
Abruzzo                                                411.447
Basilicata                                             171.232
Calabria                                               535.613
Campania                                              1538.756
Emilia-Romagna                                        1193.848
Friuli-Venezia Giulia                                  334.800
Lazio                                                 1851.134
Liguria                                                454.795
Lombardia                                             2487.629
Marche                                                 413.394
Molise                                                  92.677
Piemonte                                              1096.041
Provincia Autonoma Bolzano / Bozen                     111.839
Provincia Autonoma Trento                              121.896
Puglia                                                1012.207
Sardegna                                               419.629
Sicilia                                               1308.845
Toscana                                               1032.161
Trentino Alto Adige / Südtirol                         233.735
Umbria                                                 266.574
Valle d'Aosta / Vallée d'Aoste                          33.041
Veneto                                                1189.523

TIME                                                     \
Titolo di studio                   laurea e post-laurea
Territorio
Abruzzo                                         174.491
Basilicata                                       61.745
Calabria                                        206.190
Campania                                        625.089
Emilia-Romagna                                  664.034
Friuli-Venezia Giulia                           163.772
Lazio                                          1037.207
Liguria                                         220.237
Lombardia                                      1382.783
Marche                                          212.750
Molise                                           38.009
Piemonte                                        542.124
Provincia Autonoma Bolzano / Bozen               55.678
Provincia Autonoma Trento                        72.165
Puglia                                          399.109
Sardegna                                        188.534
Sicilia                                         474.868
Toscana                                         505.538
Trentino Alto Adige / Südtirol                  127.843
Umbria                                          127.356
Valle d'Aosta / Vallée d'Aoste                   14.816
Veneto                                          610.446

TIME                                                                                      \
Titolo di studio                   licenza di scuola elementare, nessun titolo di studio
Territorio
Abruzzo                                                                       196.968
Basilicata                                                                     95.771
Calabria                                                                      362.371
Campania                                                                      911.831
Emilia-Romagna                                                                568.828
Friuli-Venezia Giulia                                                         137.388
Lazio                                                                         596.280
Liguria                                                                       185.542
Lombardia                                                                    1170.317
Marche                                                                        231.332
Molise                                                                         50.611
Piemonte                                                                      569.290
Provincia Autonoma Bolzano / Bozen                                             51.931
Provincia Autonoma Trento                                                      55.258
Puglia                                                                        771.079
Sardegna                                                                      249.563
Sicilia                                                                       857.923
Toscana                                                                       565.068
Trentino Alto Adige / Südtirol                                                107.187
Umbria                                                                        123.716
Valle d'Aosta / Vallée d'Aoste                                                 15.412
Veneto                                                                        658.886

TIME
Titolo di studio                   licenza di scuola media
Territorio
Abruzzo                                            316.809
Basilicata                                         146.538
Calabria                                           543.729
Campania                                          1738.677
Emilia-Romagna                                    1130.415
Friuli-Venezia Giulia                              322.378
Lazio                                             1435.745
Liguria                                            409.779
Lombardia                                         2863.224
Marche                                             396.525
Molise                                              80.855
Piemonte                                          1254.661
Provincia Autonoma Bolzano / Bozen                 147.770
Provincia Autonoma Trento                          142.104
Puglia                                            1233.763
Sardegna                                           560.041
Sicilia                                           1566.351
Toscana                                            977.167
Trentino Alto Adige / Südtirol                     289.874
Umbria                                             208.049
Valle d'Aosta / Vallée d'Aoste                      38.049
Veneto                                            1339.770

#### Visualizza il seguente output

- simile a prima ma in pratica con gli "assi invertiti"
- fai attenzione che e' richiesto di visualizzare solo l'anno 2018

Territorio                                               Abruzzo           \
Sesso                                                    femmine   maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   16.432   24.255
diploma 4-5 anni (maturità)                        2018  203.683  202.849
laurea e post-laurea                               2018   95.939   74.590
licenza di scuola elementare, nessun titolo di ... 2018  122.622   72.309
licenza di scuola media                            2018  153.123  179.001

Territorio                                              Basilicata          \
Sesso                                                      femmine  maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018      7.335  10.224
diploma 4-5 anni (maturità)                        2018     83.718  87.081
laurea e post-laurea                               2018     33.779  25.728
licenza di scuola elementare, nessun titolo di ... 2018     61.638  39.335
licenza di scuola media                            2018     67.626  78.763

Territorio                                              Calabria           \
Sesso                                                    femmine   maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   14.623   18.402
diploma 4-5 anni (maturità)                        2018  259.507  273.008
laurea e post-laurea                               2018  109.964   84.041
licenza di scuola elementare, nessun titolo di ... 2018  222.118  152.158
licenza di scuola media                            2018  261.026  290.634

Territorio                                              Campania           \
Sesso                                                    femmine   maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   58.447   69.800
diploma 4-5 anni (maturità)                        2018  747.537  789.073
laurea e post-laurea                               2018  340.111  266.025
licenza di scuola elementare, nessun titolo di ... 2018  608.963  335.085
licenza di scuola media                            2018  804.849  928.129

Territorio                                              Emilia-Romagna  \
Sesso                                                          femmine
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018        140.781
diploma 4-5 anni (maturità)                        2018        596.851
laurea e post-laurea                               2018        360.395
licenza di scuola elementare, nessun titolo di ... 2018        367.388
licenza di scuola media                            2018        522.995

Territorio                                                        ...  \
Sesso                                                     maschi  ...
Titolo di studio                                   TIME           ...
diploma 2-3 anni (qualifica professionale)         2018  145.105  ...
diploma 4-5 anni (maturità)                        2018  586.221  ...
laurea e post-laurea                               2018  280.186  ...
licenza di scuola elementare, nessun titolo di ... 2018  237.071  ...
licenza di scuola media                            2018  595.485  ...

Territorio                                               Toscana           \
Sesso                                                    femmine   maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   77.693   71.498
diploma 4-5 anni (maturità)                        2018  517.479  513.230
laurea e post-laurea                               2018  292.116  226.814
licenza di scuola elementare, nessun titolo di ... 2018  363.442  219.100
licenza di scuola media                            2018  446.248  518.806

Territorio                                              Trentino Alto Adige / Südtirol  \
Sesso                                                                          femmine
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018                         63.817
diploma 4-5 anni (maturità)                        2018                        117.841
laurea e post-laurea                               2018                         71.838
licenza di scuola elementare, nessun titolo di ... 2018                         71.139
licenza di scuola media                            2018                        133.472

Territorio                                                         Umbria  \
Sesso                                                     maschi  femmine
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   75.675   16.560
diploma 4-5 anni (maturità)                        2018  109.737  132.618
laurea e post-laurea                               2018   55.627   66.348
licenza di scuola elementare, nessun titolo di ... 2018   46.498   85.785
licenza di scuola media                            2018  148.501  100.541

Territorio                                                        \
Sesso                                                     maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   23.664
diploma 4-5 anni (maturità)                        2018  130.641
laurea e post-laurea                               2018   52.226
licenza di scuola elementare, nessun titolo di ... 2018   47.605
licenza di scuola media                            2018  111.248

Territorio                                              Valle d'Aosta / Vallée d'Aoste  \
Sesso                                                                          femmine
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018                          3.115
diploma 4-5 anni (maturità)                        2018                         15.841
laurea e post-laurea                               2018                          9.077
licenza di scuola elementare, nessun titolo di ... 2018                          9.594
licenza di scuola media                            2018                         18.193

Territorio                                                        Veneto  \
Sesso                                                    maschi  femmine
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018   3.693  181.051
diploma 4-5 anni (maturità)                        2018  15.935  568.625
laurea e post-laurea                               2018   5.881  335.224
licenza di scuola elementare, nessun titolo di ... 2018   6.494  442.583
licenza di scuola media                            2018  20.345  636.058

Territorio
Sesso                                                     maschi
Titolo di studio                                   TIME
diploma 2-3 anni (qualifica professionale)         2018  231.624
diploma 4-5 anni (maturità)                        2018  623.402
laurea e post-laurea                               2018  251.950
licenza di scuola elementare, nessun titolo di ... 2018  255.176
licenza di scuola media                            2018  680.125

[5 rows x 44 columns]