# Esercizio Serie Temporali, Istruzioni

In [21]:
import pandas as pd
import datetime as dt

In [2]:
passi = pd.read_excel("steps2020.xlsx")
passi

       Steps          Date      Time
0          0   Jan 1, 2020  00:09:00
1          0   Jan 1, 2020  00:11:00
2          0   Jan 1, 2020  00:21:00
3          0   Jan 1, 2020  00:31:00
4          0   Jan 1, 2020  00:41:00
...      ...           ...       ...
18397    193  May 11, 2020  15:21:00
18398    193  May 11, 2020  15:31:00
18399    326  May 11, 2020  15:41:00
18400    326  May 11, 2020  15:51:00
18401    326  May 11, 2020  15:52:00

[18402 rows x 3 columns]

In [3]:
passi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18402 entries, 0 to 18401
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Steps   18402 non-null  int64
 1   Date    18402 non-null  object
 2   Time    18402 non-null  object
dtypes: int64(1), object(2)
memory usage: 431.4+ KB

###### Il dataset contiene il numero di passi percorsi a partire da 01/01/2020 all' 11/05/2020 alle ore 15:52
    
- il numero di passi mostrato e' cumulativo per giornata, quindi ad ogni nuova giornata parte da zero e l'ultima osservazione di giornata (tipicamente alle 23:59:00) contiene il numero totale di passi percorsi in quel giorno

#### 1) Sposta a indice le informazioni relative al tempo


il risultato finale deve essere il seguente:
- index: contiene le informazioni relative al tempo (anno-mese-giorno ora-minuti-secondi)
- l'indice e' nominato "TEMPO"
- c'e' solo una colonna che contiene le info relative ai passi

In [5]:
#passi['TEMPO'] = passi['Date'] + ' ' + passi['Time']
#passi.set_index(pd.to_datetime(passi['TEMPO']), inplace=True)
passi.drop(['Date', 'Time'], axis = 1,inplace=True)

##### 2) trova il giorno con il numero maggiore di passi
- ricorda che l'ultima osservazione di ogni giornata contiene il numero totale di passi per quel giorno

In [6]:
max_passi = passi.resample('D').last()
max_passi.nlargest(1, 'Steps')

            Steps                  TEMPO
TEMPO
2020-01-15  21016  Jan 15, 2020 23:59:00

#### 3) Riordina il dataframe in base al numero totale di passi percorsi settimanalmente, a partire dalla settimana con piu' passi totali

In [7]:
max_passi.drop(['TEMPO'], axis=1, inplace=True)
passi_ordinati = max_passi.resample('W', kind='period').sum()
passi_ordinati.sort_values(by='Steps', ascending=False)

C:\Users\G.Zaffinelli-cons\AppData\Local\Temp\ipykernel_20452\312505585.py:2: FutureWarning: The 'kind' keyword in DataFrame.resample is deprecated and will be removed in a future version. Explicitly cast the index to the desired type instead
  passi_ordinati = max_passi.resample('W', kind='period').sum()

                       Steps
TEMPO
2020-03-02/2020-03-08  88938
2020-01-27/2020-02-02  84216
2020-01-13/2020-01-19  68390
2020-02-10/2020-02-16  67109
2020-02-17/2020-02-23  64983
2020-02-24/2020-03-01  64237
2020-03-16/2020-03-22  60974
2020-02-03/2020-02-09  59376
2020-03-09/2020-03-15  58568
2020-01-20/2020-01-26  58274
2020-05-04/2020-05-10  44635
2020-04-27/2020-05-03  42508
2020-04-20/2020-04-26  33723
2020-01-06/2020-01-12  29584
2019-12-30/2020-01-05  26348
2020-03-23/2020-03-29  24385
2020-04-13/2020-04-19  24096
2020-04-06/2020-04-12  19033
2020-03-30/2020-04-05  17038
2020-05-11/2020-05-17    326

#### 4) parte 1: calcola il numero totale di passi percorsi in media ogni giorno per ogni mese
- l'output deve essere come il seguente:

In [14]:
media_passi = max_passi.resample('M', kind='period').mean()
media_passi

C:\Users\G.Zaffinelli-cons\AppData\Local\Temp\ipykernel_20452\3605267664.py:1: FutureWarning: The 'kind' keyword in DataFrame.resample is deprecated and will be removed in a future version. Explicitly cast the index to the desired type instead
  media_passi = max_passi.resample('M', kind='period').mean()
C:\Users\G.Zaffinelli-cons\AppData\Local\Temp\ipykernel_20452\3605267664.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  media_passi = max_passi.resample('M', kind='period').mean()

               Steps
TEMPO
2020-01  8082.645161
2020-02  9189.689655
2020-03  7833.548387
2020-04  3480.200000
2020-05  6584.727273

 #### 4) parte 2: come punto sopra ma ogni mese deve essere indicato per nome come nell'output sotto
 - suggerimento: attenzione al parametro "kind" e alla trasformazione in DatetimeIndex o PeriodIndex

In [22]:
media_passi.index= max_passi.resample('M').mean().index.month_name()
media_passi

C:\Users\G.Zaffinelli-cons\AppData\Local\Temp\ipykernel_20452\863020505.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  media_passi.index= max_passi.resample('M').mean().index.month_name()

                Steps
TEMPO
January   8082.645161
February  9189.689655
March     7833.548387
April     3480.200000
May       6584.727273